services:
  authentik:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_VERSION}
    user: "1000:1000"
    environment:
      AUTHENTIK_REDIS__HOST: ${REDIS_NAME}
      AUTHENTIK_POSTGRESQL__HOST: ${POSTGRES_NAME}
      AUTHENTIK_POSTGRESQL__USER: ${POSTGRES_USER}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${POSTGRES_PASSWORD}
      AUTHENTIK_POSTGRESQL__NAME: ${POSTGRES_USER}
    environment:
      - AUTHENTIK_DISABLE_UPDATE_CHECK
      - AUTHENTIK_ERROR_REPORTING__ENABLED
      - AUTHENTIK_DISABLE_STARTUP_ANALYTICS
      - AUTHENTIK_AVATARS
      - AUTHENTIK_SECRET_KEY
    volumes:
      - "./media:/media"
      - "./custom-templates:/templates"
    restart: unless-stopped